version: '3.7'
services: 
    api:
        build: .
        depends_on: 
            - mongodb
        environment: 
            - MONGO_URI="mongodb+srv://freakles:pass1234@cluster0.l6s6g.mongodb.net"
        ports: 
            - "8080:8080"
        container_name: bug-tracker-api

    mongodb:
        image: mongo
        ports: 
            - "27017-27017"
        volumes:
            - db-data:/data/db
        container_name: bug-tracker-db
        

volumes:
    db-data: